### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by efleurine** [EvanBacon/react-native-fastest-image#1]

**Comment by efleurine** [comment]
Hi thanks for this incredibly fast library.

I am wondering how much MB does this add to my app bundle.

Thanks

**Comment by EvanBacon** [comment]
this does not add anything to the app bundle, but I'd recommend keeping an eye out for expo-image package since it'll actually be a "fastest-image" https://github.com/expo/expo/tree/master/packages/expo-image (still wip right now though)
